Fix quick reference documentation for 'exec'
`exec` was a statement in Python 2.7, but it's a function in Python 3+.

Following the old quickref line triggers a `SyntaxError` on Python 3:

```
In [2]: exec _i1
  File "<ipython-input-12-f8fcb58cbaa6>", line 1
    exec _i1
         ^
SyntaxError: Missing parentheses in call to 'exec'
```

But it is fixed with the parentheses:

```
In [3]: exec(_i1)
```