Backport PR #2796: P3K: fix cookie parsing under Python 3.x (+ duplicate import is removed)
This fixes
```
WARNING:root:couldn't parse cookie string: b'__utma=96992031.448119963.1345042395.1345203014.1351851470.3; __utmz=96992031.1345042395.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); sessionid=2456b59cebe2a3c7075c6d3f1d136c36; csrftoken=I9knGxQWHWXSUAeOXihXlzs0IJxbss07'
Traceback (most recent call last):
  File "/Users/kmike/envs/pymorphy-33/lib/python3.3/site-packages/ipython-0.14.dev-py3.3.egg/IPython/frontend/html/notebook/handlers.py", line 441, in _inject_cookie_message
    self.request._cookies = http.cookies.SimpleCookie(msg)
  File "/usr/local/Cellar/python3/3.3.0/Frameworks/Python.framework/Versions/3.3/lib/python3.3/http/cookies.py", line 476, in __init__
    self.load(input)
  File "/usr/local/Cellar/python3/3.3.0/Frameworks/Python.framework/Versions/3.3/lib/python3.3/http/cookies.py", line 524, in load
    for key, value in rawdata.items():
AttributeError: 'bytes' object has no attribute 'items'
```

warning under Python 3.x