ENH: Accept one-off exception mode setting for %tb.
This makes it easy to access a more verbose representation that the
currently-active exception reporting mode provides.

```python
In [1]: %xmode minimal
Exception reporting mode: Minimal

In [2]: def f():
   ...:     3/0
   ...:

In [3]: f()
ZeroDivisionError: division by zero

In [4]: %tb verbose
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-3-c43e34e6d405> in <module>
----> 1 f()
        global f = <function f at 0x10e52de18>

<ipython-input-2-cd4172d70b5b> in f()
      1 def f():
----> 2     3/0
      3

ZeroDivisionError: division by zero

In [5]: f()  # The default reporting mode has not been changed....
ZeroDivisionError: division by zero
```