Backport PR #2773: Fixed minor typo causing AttributeError to be thrown.
I'm not sure how I caused the error to be thrown and couldn't reproduce it with the same call again, nevertheless I think the fix is correct.

```python
In [21]: rc.shutdown(hub=True)
Traceback (most recent call last):

  File "<ipython-input-21-977a05a15f31>", line 1, in <module>
    rc.shutdown(hub=True)

  File "<string>", line 2, in shutdown

  File "c:\dev\code\ipython\IPython\parallel\client\client.py", line 69, in spin_first
    self.spin()

  File "c:\dev\code\ipython\IPython\parallel\client\client.py", line 1005, in spin
    self._flush_notifications()

  File "c:\dev\code\ipython\IPython\parallel\client\client.py", line 800, in _flush_notifications
    raise Exception("Unhandled message type: %s"%msg.msg_type)

AttributeError: 'dict' object has no attribute 'msg_type'
```